version: '2'

services:
  haproxy:
    image: haproxy
    restart: on-failure:10
    depends_on:
     - server
    network_mode: "host"
    ports:
     - "80:80"
    volumes:
     - /data/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
  server:
    image: bodar/teamcity-server
    restart: on-failure:10
    depends_on:
     - postgres
    ports:
     - "127.0.0.1:8111:8111"
    volumes:
     - /data/BuildServer:/data/BuildServer
    environment:
      POSTGRES_DB: teamcity
      POSTGRES_USER: teamcity_admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TEAMCITY_RESTORE_URL: ${TEAMCITY_RESTORE_URL}
  agent:
    image: bodar/teamcity-agent
    restart: on-failure:10
    depends_on:
     - server
    environment:
      TEAMCITY_SERVER_URL: http://server:8111
  postgres:
    image: postgres:9.5
    restart: on-failure:10
    volumes:
     - /data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: teamcity
      POSTGRES_USER: teamcity_admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}


