version: '2'

services:
  server:
    image: bodar/teamcity-server
    restart: on-failure:10
    ports:
     - "80:8111"
    volumes:
     - /data/BuildServer:/data/BuildServer
  agent1:
    image: bodar/teamcity-agent
    restart: on-failure:10
    depends_on:
     - server
    environment:
      TEAMCITY_SERVER_URL: http://server:8111

