#!/usr/bin/env bash

if [ ! -f ${TEAMCITY_DATA_PATH}/config/database.properties ]; then
  mkdir -p ${TEAMCITY_DATA_PATH}/config/
  envsubst < /opt/TeamCity/database.properties.template > ${TEAMCITY_DATA_PATH}/config/database.properties
fi

exec /opt/TeamCity/bin/teamcity-server.sh run

